version: '3'

services:
  postgres:
    image: postgres:9.6
    hostname: postgres
    networks:
      - test
    environment:
      - POSTGRES_PASSWORD=postgres

  #
  # Zookeeper configurtion
  # Based on
  # https://hub.docker.com/_/zookeeper
  #
  zoo1:
    image: zookeeper
    hostname: zoo1
    networks:
      - test
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper
    hostname: zoo2
    networks:
      - test
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    depends_on:
      - zoo1

  zoo3:
    image: zookeeper
    hostname: zoo3
    networks:
      - test
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    depends_on:
      - zoo2

  #
  # Kafka configuration for single node cluster
  # Based on
  # https://docs.confluent.io/current/installation/docker/config-reference.html#confluent-kafka-configuration
  #
  kafka1:
    image: confluentinc/cp-kafka
    hostname: kafka1
    networks:
      - test
    volumes:
      - /data/kafka-logs:/tmp/kafka-logs
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CONFLUENT_SUPPORT_METRICS.ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  #
  # Kafka connect configuration
  # Based on
  # https://docs.confluent.io/current/installation/docker/config-reference.html#kafka-connect-configuration 
  #
  kafka-connect:
    image: confluentinc/cp-kafka-connect
    hostname: kafka-connect
    ports:
      - 18083:8083
    networks:
      - test
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafka1:9092
      - CONNECT_GROUP_ID=test
      - CONNECT_CONFIG_STORAGE_TOPIC=test-config
      - CONNECT_OFFSET_STORAGE_TOPIC=test-offsets
      - CONNECT_STATUS_STORAGE_TOPIC=test-status
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_REST_ADVERTISED_HOST_NAME=localhost
      - CONNECT_PLUGIN_PATH=/usr/share/java
      # Replication factor should be configured according to num of kafka nodes
      - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
      - kafka1
      - postgres

networks:
  test:
