# https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/mirror-maker/kafka-mirror-maker-2.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
spec:
  version: 3.4.0
  replicas: 1
  connectCluster: "my-target-cluster"
  clusters:
    - alias: "my-source-cluster"
      bootstrapServers: my-cluster-kafka-bootstrap:9092
    - alias: "my-target-cluster"
      # bootstrapServers of TARGET cluster SHOULD be the service
      # for bootstrap server which is exposed for clients accessing brokers
      # See https://strimzi.io/docs/operators/latest/configuring.html#ref-list-of-kafka-cluster-resources-str
      #
      # In this sample my-cluster-kafka-external-bootstrap the one.
      #
      # $ kubectl get services -n kafka
      # NAME                                  TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)                               AGE
      # my-cluster-kafka-0                    LoadBalancer   10.0.64.105   bb.cc.dd.ee     9094:31394/TCP                        4m39s
      # my-cluster-kafka-bootstrap            ClusterIP      10.0.71.66    <none>          9091/TCP,9092/TCP,9093/TCP            4m39s
      # my-cluster-kafka-brokers              ClusterIP      None          <none>          9090/TCP,9091/TCP,9092/TCP,9093/TCP   4m39s
      # my-cluster-kafka-external-bootstrap   LoadBalancer   10.0.79.170   xx.yy.zz.aa     9094:31845/TCP                        4m39s
      # my-cluster-zookeeper-client           ClusterIP      10.0.68.221   <none>          2181/TCP                              7m55s
      # my-cluster-zookeeper-nodes            ClusterIP      None          <none>          2181/TCP,2888/TCP,3888/TCP            7m54s
      bootstrapServers: xx.yy.zz.aa:9094
      config:
        # -1 means it will use the default replication factor configured in the broker
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
      # Public key of CA cert generated by operator on target cluster
      # will be required to verify the server certificate.
      # To obtain see https://strimzi.io/docs/operators/latest/configuring.html#proc-accessing-kafka-using-loadbalancers-str
      #
      # The obtained certificate will be used in trustedCertificate property.
      # See https://strimzi.io/docs/operators/latest/configuring.html#con-common-configuration-trusted-certificates-reference
      tls:
        trustedCertificates:
          - secretName: green-my-cluster-cluster-ca-cert
            certificate: green-ca.crt
  mirrors:
    - sourceCluster: "my-source-cluster"
      targetCluster: "my-target-cluster"
      sourceConnector:
        config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: "false"
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
      topicsPattern: ".*"
      groupsPattern: ".*"
